version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=FIKRW0iC3LbH
      - POSTGRES_DB=verceldb
    ports:
      - 'ep-sparkling-thunder-a4a84man-pooler.us-east-1.aws.neon.tech:5432'